# Generated by Django 4.1.6 on 2023-02-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_text',
            new_name='body',
        ),
    ]
